name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r s2_organisation_and_version_control/exercise_files/mlops/requirements.txt
        pip install -r s2_organisation_and_version_control/exercise_files/mlops/requirements_tests.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
